esphome:
  name: camara1
  platform: ESP32
  board: nodemcu-32s

wifi: 
  ssid: "ssid"
  password: "password"

  ap:
    ssid: "Camera"
    password: "password"

api: 
  password: "jaqueriacamara1"
ota:
  password: "jaqueriacamara1"

#ESP32CAM
esp32_camera:
  name: Camara 1
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO17, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15
  resolution: 800x600
  #max_framerate: 60
  jpeg_quality: 10

#Luz
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: camara1 light
