version: '3'
networks: 
  wordpress: 
    driver: bridge
services:
  db:
    image: mysql:8.0.24
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${PASSWORDMYSQL}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - wordpress
      
  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${USERWORD}
      WORDPRESS_DB_PASSWORD: ${PASSWORDWORD}
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
    volumes:
      - $PWD/wordpress:/var/www/html
    networks:
      - wordpress
    depends_on: 
      - db