version: '3'
networks: 
  my-network: 
    driver: bridge
volumes:
  openldap_data:
    driver: local
services: 
  openldap: 
    container_name: openldap
    image: bitnami/openldap:2.4.58
    ports: 
      - '1389:1389'
      - '1636:1636'
    environment: 
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_ROOT=dc=lajaqueria,dc=org
    networks: 
      - my-network
    volumes: 
      - 'openldap_data:/bitnami/openldap'
      
  homeassistant: 
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    ports: 
      - '8123:8123'
    volumes: 
      - /home/usuario/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - my-network 
  phpldapadmin: 
    container_name: phpldapadmin
    image: rschaeuble/phpldapadmin
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS="openldap"
      - PHPLDAPADMIN_HTTPS="false"
      - LDAP_URL=ldap://openldap:1389
      - LDAP_BASE=dc=lajaqueria,dc=org
      - LDAP_ADMIN=cn=admin,dc=lajaqueria,dc=org
      #ENV LDAP_CERTS: /data/ldap-server-certificate.crt
    ports: 
      - "80:80"
    links:
      - "openldap"
    depends_on: 
      - openldap
    networks: 
      - my-network
      
