version: '2'
networks: 
  my-network: 
    driver: bridge
volumes:
  openldap_data:
    driver: local
services: 
  openldap: 
    image: osixia/openldap:latest
    container_name: openldap
    environment: 
      LDAP_ORGANISATION: "LaJaqueria.org"
      LDAP_DOMAIN: "lajaqueria.org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
    tty: true
    stdin_open : true
    networks: 
      - my-network
    volumes: 
      - ./ldap_dbase:/var/lib/ldap
      - ./ldap_config:/etc/lib/ldap
      - ./ldap_certs:/container/service/slapd/assets/certs/
    ports:
      - "1389:1389"
      - "1636:1636"
    domainname: "lajaqueria.org"
    hostname: "lajaqueria.org"
  
  phpldapadmin: 
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment: 
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
      #LDAP_URL=ldap://openldap:1389
      #LDAP_BASE=dc=lajaqueria,dc=org
      #LDAP_ADMIN=cn=admin,dc=lajaqueria,dc=org
      #ENV LDAP_CERTS: /data/ldap-server-certificate.crt
    ports: 
      - "80:80"
    depends_on: 
      - openldap
    networks: 
      - my-network
      
  homeassistant: 
      container_name: homeassistant
      image: homeassistant/home-assistant:stable
      ports: 
        - '8123:8123'
      volumes: 
        - /home/administrador/config:/home/administrador/homeassistant
        - /etc/localtime:/etc/localtime:ro
      restart: unless-stopped
      networks:
        - my-network
