version: '3'
networks: 
  my-network: 
    driver: bridge
volumes:
  openldap_data:
    driver: local
services: 
  openldap: 
    container_name: openldap
    image: bitnami/openldap:2.4.58
    ports: 
      - '1389:1389'
      - '1636:1636'
    environment: 
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_ROOT=dc=lajaqueria,dc=org
    networks: 
      - my-network
    volumes: 
      - 'openldap_data:/bitnami/openldap'
      
  homeassistant: 
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    ports: 
      - '8123:8123'
    volumes: 
      - /home/administrador/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - my-network 
  phpldapadmin: 
    container_name: phpldapadmin
    image: rschaeuble/phpldapadmin
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS="openldap"
      - PHPLDAPADMIN_HTTPS="false"
      - LDAP_URL=ldap://openldap:1389
      - LDAP_BASE=dc=lajaqueria,dc=org
      - LDAP_ADMIN=cn=admin,dc=lajaqueria,dc=org
      #ENV LDAP_CERTS: /data/ldap-server-certificate.crt
    ports: 
      - "80:80"
    links:
      - "openldap"
    depends_on: 
      - openldap
    networks: 
      - my-network

  mosquitto: 
    image: eclipse-mosquitto
    container_name: mosquitto
    ports: 
      - "1883:1883"
      - "9001:9001"
    volumes:  
      - /home/administrador/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      #- mosquitto-data:/mosquitto/data 
      #- mosquitto-logs:/mosquitto/logs
      #- mosquitto-conf:/mosquitto/config
      # no se si estas son correctas
    networks:
      - my-network


      
      #Da el siguiente error:
 #Creating mosquitto ... error

#ERROR: for mosquitto  Cannot start service mosquitto: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/home/administrador/mosquitto/mosquitto.conf" to rootfs at "/var/lib/docker/overlay2/c8698f29823c31fec6f308d077b9cf4bbec589e5e53693e5ddd928389c29677e/merged/mosquitto/config/mosquitto.conf" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

#ERROR: for mosquitto  Cannot start service mosquitto: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/home/administrador/mosquitto/mosquitto.conf" to rootfs at "/var/lib/docker/overlay2/c8698f29823c31fec6f308d077b9cf4bbec589e5e53693e5ddd928389c29677e/merged/mosquitto/config/mosquitto.conf" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
#ERROR: Encountered errors while bringing up the project.