version: '3'
networks: 
  my-network: 
    driver: bridge
volumes:
  openldap_data:
    driver: local
services: 
  openldap: 
    container_name: openldap
    image: bitnami/openldap:2.4.58
    ports: 
      - '1389:1389'
      - '1636:1636'
    environment: 
      - LDAP_ADMIN_USERNAME=${LDAP_ADMINUSER}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMINPASS}
      - LDAP_ROOT=${LDAP_ROOT_DOMAIN}
    networks: 
      - my-network
    restart: unless-stopped
    volumes: 
      - 'openldap_data:/bitnami/openldap'
      
  homeassistant: 
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    ports: 
      - '8123:8123'
    volumes: 
      - $PWD/hconfig:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on: 
      - mosquitto
    networks:
      - my-network 
  phpldapadmin: 
    container_name: phpldapadmin
    image: rschaeuble/phpldapadmin
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS="openldap"
      - PHPLDAPADMIN_HTTPS="false"
      - LDAP_URL=ldap://openldap:1389
      - LDAP_BASE=${LDAP_ROOT_DOMAIN}
      - LDAP_ADMIN=cn=${LDAP_ADMINUSER},${LDAP_ROOT_DOMAIN}
      #ENV LDAP_CERTS: /data/ldap-server-certificate.crt
    ports: 
      - "80:80"
    links:
      - "openldap"
    depends_on: 
      - openldap
    restart: unless-stopped
    networks: 
      - my-network

  mosquitto: 
    image: eclipse-mosquitto:1.6
    container_name: mosquitto
    ports: 
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    volumes:  
      - $PWD/mconfig:/mosquitto/config/
      #- mosquitto-data:/mosquitto/data 
      #- mosquitto-logs:/mosquitto/logs
      #- mosquitto-conf:/mosquitto/config
      # no se si estas son correctas
    networks:
      - my-network
 
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - /home/administrador/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    networks:
      - my-network
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
      