esphome:
  name: lectornfc
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: "LAJAQUERIA"
  password: "password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lectornfc Fallback Hotspot"
    password: "HlobYi8l2xIN"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "password"

ota:
  password: "password"

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

rc522_spi:
  cs_pin: GPIO15
