esphome:
  name: temperatura
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "MiFibra-273F"
  password: "hmuuuEN9"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperatura Fallback Hotspot"
    password: "hmuuuEN9"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "jaqueriatemp"
ota: 
  password: "jaqueriatemp"
sensor:
  - platform: dht
    pin: D13
    temperature:
      name: "Medidor de temperatura de la sede"
    humidity:
      name: "Medidor de humedad de la sede"
    update_interval: 300s